# Generated by Django 3.0.2 on 2020-10-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmuser',
            name='is_admin',
        ),
    ]
